=== Maritims/opencargo/src/main/xsd/rules.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="common.xsd"/>

    <xs:complexType name="TargetDTO">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="consignor" type="IdentifiableEntityDTO"/>
            <xs:element name="product" type="IdentifiableEntityDTO"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="RuleBaseDTO" abstract="true">
        <xs:complexContent>
            <xs:extension base="IdentifiableEntityDTO">
                <xs:sequence>
                    <xs:element name="number" type="xs:string"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="priority" type="PriorityDTO"/>
                    <xs:element name="targets" type="TargetDTO"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="RangeRuleDTO">
        <xs:complexContent>
            <xs:extension base="RuleBaseDTO">
                <xs:sequence>
                    <xs:element name="minInclusive" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="maxExclusive" type="xs:decimal" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="LengthOrGirthRuleDTO">
        <xs:complexContent>
            <xs:extension base="RuleBaseDTO">
                <xs:sequence>
                    <xs:element name="maxLength" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="maxLengthAndGirthCombined" type="xs:decimal" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="MinDimensionsRuleDTO">
        <xs:complexContent>
            <xs:extension base="RuleBaseDTO">
                <xs:sequence>
                    <xs:element name="minWidth" type="PositiveDecimalDTO" minOccurs="0"/>
                    <xs:element name="minLength" type="PositiveDecimalDTO" minOccurs="0"/>
                    <xs:element name="minHeight" type="PositiveDecimalDTO" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GeographyRuleDTO">
        <xs:complexContent>
            <xs:extension base="RuleBaseDTO">
                <xs:sequence>
                    <xs:element name="countrySpecification" type="CountrySpecificationDTO" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="RuleListDTO">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="geographyRule" type="GeographyRuleDTO"/>
            <xs:element name="weightRule" type="RangeRuleDTO"/>
            <xs:element name="widthRule" type="RangeRuleDTO"/>
            <xs:element name="lengthRule" type="RangeRuleDTO"/>
            <xs:element name="heightRule" type="RangeRuleDTO"/>
            <xs:element name="lengthOrGirthRule" type="LengthOrGirthRuleDTO"/>
            <xs:element name="minDimensionsRule" type="MinDimensionsRuleDTO"/>
        </xs:choice>
    </xs:complexType>

    <xs:element name="rules" type="RuleListDTO"/>
</xs:schema>

=== Maritims/opencargo/src/main/resources/rules.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../xsd/rules.xsd">
    <geographyRule id="1">
        <number>1</number>
        <name>Posten Norge er kun tilgjengelig i Norge</name>
        <priority>0</priority>
        <targets>
            <product id="1"/>
            <product id="2"/>
        </targets>
        <countrySpecification>
            <countryCode>NO</countryCode>
            <postalCodeSpecification xsi:type="PostalCodeRangeSpecificationDTO" minInclusive="0001" maxInclusive="9999"/>
            <postalCodeSpecification xsi:type="PostalCodeSetSpecificationDTO">
                <postalCode>3261</postalCode>
            </postalCodeSpecification>
        </countrySpecification>
    </geographyRule>
    <weightRule id="2">
        <number>2</number>
        <name>Pakke til hentested har en maksimum vekt på 35 kilo</name>
        <priority>0</priority>
        <targets>
            <product id="1"/>
        </targets>
        <maxExclusive>35.0</maxExclusive>
    </weightRule>
    <weightRule id="3">
        <number>3</number>
        <name>Pakkeboks har en maskimumvekt på 10 kilo</name>
        <priority>0</priority>
        <targets>
            <product id="2"/>
        </targets>
        <maxExclusive>10.0</maxExclusive>
    </weightRule>
    <minDimensionsRule id="3">
        <number>4</number>
        <name>Pakke til hentested har minimumsmål 15 x 10 x 1 cm</name>
        <priority>0</priority>
        <targets>
            <product id="1"/>
            <product id="2"/>
        </targets>
        <minWidth>15.0</minWidth>
        <minLength>10.0</minLength>
        <minHeight>1.0</minHeight>
    </minDimensionsRule>
    <lengthOrGirthRule id="4">
        <number>5</number>
        <name>Pakke til hentested kan enten være maksimalt 240 cm lang, eller ha en maks lengde + omkrets på 360 cm</name>
        <priority>0</priority>
        <targets>
            <product id="1"/>
            <product id="2"/>
        </targets>
        <maxLength>240.0</maxLength>
        <maxLengthAndGirthCombined>360.0</maxLengthAndGirthCombined>
    </lengthOrGirthRule>
</rules>
